### ISSUE TITLE
OnEntry() of State is called before OnEntry() of StateGroup

### ISSUE THREAD

**Issue by rodja** [canton7/StateMechanic#3]
When entering a State within a StateGroup the OnEntry() method of the State is executed first: (see https://github.com/canton7/StateMechanic/blob/develop/src/StateMechanic/StateMachine%601.cs#L253).

I think this behavior is unwanted because it is asymmetric to the OnExit calls. For example when registering to some event or allocating resources for the whole StateGroup they should available for consumption in the OnEntry methods of the States within. When leaving the group the OnExit unregister/releases them. I believe the StateGroup works as a braked for a list of States and therefore their OnEntry should be executed first and their OnExit last.

**Comment by canton7** [comment]
Yep, I agree

**Comment by canton7** [comment]
Released as 1.0.3
