### ISSUE TITLE
hsm

### ISSUE THREAD

**Issue by davidwallis3101** [canton7/StateMechanic#5]
I was looking at stateless initially but stumbled across this page :) 
I am thinking about a statemachine for home automation with some logic similar to this (in stateless):

    var stateMachine = new StateMachine<State, Trigger>(State.UnOccupied);

            stateMachine.OnTransitioned(OnTransitionedAction);

            stateMachine.Configure(State.UnOccupied)
                .Permit(Trigger.SensorActivity, State.Occupied)
                .PermitReentry(Trigger.AlarmFullSet);

            stateMachine.Configure(State.Occupied)
                .Permit(Trigger.AlarmFullSet, State.UnOccupied)
                .Permit(Trigger.AlarmPartSet, State.Asleep)
                .PermitReentry(Trigger.SensorActivity);

            stateMachine.Configure(State.Asleep)
                .SubstateOf(State.Occupied)
                .Permit(Trigger.AlarmUnset, State.Occupied);

            stateMachine.OnUnhandledTrigger((state, trigger) =>
            {
                //TODO Log
                Console.WriteLine("Unhandled: '{0}' state, '{1}' trigger!");
            });

![image](https://user-images.githubusercontent.com/13855486/27438301-b535bd9c-575c-11e7-9a91-35001fe705ac.png)

However I want to represent the state of rooms within a house and also the overall state of the house..

IE

    Home
    
        House Object
                            Upstairs
                                            Bedroom 1
                                            Bedroom 2
                            Downstairs
                                            Kitchen
                                            Living Room

        Garden
                            Front
                            Back
                            Side                       

So if Living room is occupied then so is the downstairs and the house and the home.. 

Apologies in advance my C# isn't the best and I am throwing myself in at the deep end!

Also is it possible to do timed leaving of states.. so a sensor could trigger a room to be occupied, then more activity triggers ‘reentrant?’ (Restarts a counter / timer / adjusts a schedule) on an occupied state entry – then after 15mins of no more entry/activity events, occupancy clears on that area and the state transitions to unoccupied for that area.

**Comment by canton7** [comment]
For your first question, I'd do this with a simple hierarchy of objects instead of using state machines. Have a Location object (modelling a house, garden, Upstairs, etc), and a Room object (Bedroom 1, etc) which has your state machine in it. The Location object has a collection of children (so House has a collection containing Upstairs and Downstairs). When you ask House whether it's occupied, it checks Upstairs and Downstairs. Upstairs checks Bedrooms 1 and 2, etc.

You could create a timer which fires a trigger after a delay.

**Comment by canton7** [comment]
Closing as no response
